In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df_hw = pd.read_csv(url)

In [4]:
df_hw.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df_hw.shape

(10000, 11)

In [7]:
df_hw['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
df_hw.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
(df_hw.isnull().sum() > 0).sum()

np.int64(2)

In [10]:
df_hw.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [12]:
df_hw['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [13]:
median_before = df_hw['horsepower'].median()
median_before

np.float64(254.0)

In [14]:
mean_hp = df_hw['horsepower'].mean()
mean_hp

np.float64(254.44601556505535)

In [15]:
df_filled = df_hw.copy()
df_filled['horsepower'] = df_filled['horsepower'].fillna(mean_hp)

In [16]:
median_after = df_filled['horsepower'].median()
median_after

np.float64(254.44601556505535)

In [17]:
median_before, median_after

(np.float64(254.0), np.float64(254.44601556505535))

In [18]:
mode_hp = df_hw['horsepower'].mode()[0]
mode_hp

np.float64(252.0)

In [19]:
median_before = df_hw['horsepower'].median()

df_mode = df_hw.copy()
df_mode['horsepower'] = df_mode['horsepower'].fillna(mode_hp)

median_after = df_mode['horsepower'].median()

median_before, median_after

(np.float64(254.0), np.float64(252.0))

In [21]:
import numpy as np

In [27]:
asia = df_hw[df_hw['origin'] == 'Asia']

In [28]:
asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [29]:
asia = asia[['vehicle_weight', 'model_year']]

In [30]:
asia = asia.head(7)
asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [31]:
X = asia.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [32]:
X.shape

(7, 2)

In [33]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [34]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [36]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [37]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [39]:
w.sum()

np.float64(0.36919696904925486)